services:
  db:
    image: postgres:latest
    container_name: kata-person-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kata_person
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: kata-person-app
    volumes:
      - .:/app 
    working_dir: /app 
    environment:
      - FLASK_APP=src/core/main.py
      - FLASK_ENV=development
      - PYTHONPATH=/app 
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: