"""Creación de tabla person

Revision ID: 490ac9f84ab6
Revises: 
Create Date: 2025-02-20 17:55:45.636164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490ac9f84ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=200), nullable=False),
    sa.Column('additional_name', sa.String(length=200), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
